const similarData = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/n9QCm8uagvmXH476u5qFQsW8HkU.jpg",
      genre_ids: [Array],
      id: 348892,
      original_language: "hi",
      original_title: "बजरंगी भाईजान",
      overview:
        "A young mute girl from Pakistan loses herself in India with no way to head back. A devoted man with a magnanimous spirit undertakes the task to get her back to her motherland and unite her with her family.",
      popularity: 16.308,
      poster_path: "/rNfToRJw35h7a4y6HXGRgfkLvdc.jpg",
      release_date: "2015-07-17",
      title: "Bajrangi Bhaijaan",
      video: false,
      vote_average: 7.8,
      vote_count: 427,
    },
    {
      adult: false,
      backdrop_path: "/msgutegakwajb9vjC3Xgh4t7e0M.jpg",
      genre_ids: [Array],
      id: 348893,
      original_language: "en",
      original_title: "Boyka: Undisputed IV",
      overview:
        "In the fourth installment of the fighting franchise, Boyka is shooting for the big leagues when an accidental death in the ring makes him question everything he stands for. When he finds out the wife of the man he accidentally killed is in trouble, Boyka offers to fight in a series of impossible battles to free her from a life of servitude.",
      popularity: 68.934,
      poster_path: "/7QGdIJWWTkPhVjpQ0zA6z69khod.jpg",
      release_date: "2016-08-01",
      title: "Boyka: Undisputed IV",
      video: false,
      vote_average: 7.112,
      vote_count: 1179,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [Array],
      id: 348901,
      original_language: "en",
      original_title: "Gutterdämmerung",
      overview:
        'The "Devil\'s Evil Guitar" has been removed from the world by the supreme being, and rock and roll is a thing of the past in this newly puritanical environment. But what happens when the guitar is sent back by Vicious, an angel punk?',
      popularity: 1.241,
      poster_path: "/iaLjMNFLMGNK4xTgkxC3EcfJwd9.jpg",
      release_date: "2016-05-06",
      title: "Gutterdämmerung",
      video: false,
      vote_average: 5.8,
      vote_count: 2,
    },
    {
      adult: false,
      backdrop_path: "/2cKkruj9Q6t0O3OYHaV0dlNFW89.jpg",
      genre_ids: [Array],
      id: 191502,
      original_language: "en",
      original_title: "The Unbelievers",
      overview:
        "Scientists Richard Dawkins and Lawrence Krauss travel the globe promoting a scientific worldview and the rational questioning of religious belief.",
      popularity: 6.582,
      poster_path: "/e3rRgbUY2Fon26zwJMkei9b26hg.jpg",
      release_date: "2013-12-13",
      title: "The Unbelievers",
      video: false,
      vote_average: 6.458,
      vote_count: 120,
    },
    {
      adult: false,
      backdrop_path: "/vvfug7jtrimjvZg1ZitIq73gnRO.jpg",
      genre_ids: [Array],
      id: 348514,
      original_language: "en",
      original_title: "Red Rover",
      overview:
        "Two teenagers from a remote religious community travel to town in search of shelter after being told by their Evangelical parents that an asteroid will soon destroy the earth.",
      popularity: 1.335,
      poster_path: "/89llvEzXJOA467ZtRAXGZMmIFpc.jpg",
      release_date: "2015-10-30",
      title: "Red Rover",
      video: false,
      vote_average: 5.75,
      vote_count: 8,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [Array],
      id: 1042228,
      original_language: "ja",
      original_title: "爆竜戦隊アバレンジャー20th: 許されざるアバレ",
      overview:
        "Bakuryuu Sentai Abaranger 20th: The Unforgivable Abare is an upcoming Japanese tokusatsu superhero movie commemorating the 20th anniversary of Bakuryuu Sentai Abaranger TV series.",
      popularity: 8.688,
      poster_path: "/8iX8xEGIqLPufvczDjKUzM3YcVe.jpg",
      release_date: "2023-09-01",
      title: "Bakuryū Sentai Abarenjā 20th: Yurusa Rezaru Abare",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/oQ4ILVc1EiSH3OLwJi4HiJ7mxQu.jpg",
      genre_ids: [Array],
      id: 1042555,
      original_language: "en",
      original_title: "Alone Together",
      overview:
        "When an evil presence enters her home, a young girl must confront the dark past of her relationship and her faith.",
      popularity: 0.6,
      poster_path: "/62vPKGGTA2fxirPL9fwZvh9zsr5.jpg",
      release_date: "2021-01-23",
      title: "Alone Together",
      video: false,
      vote_average: 6,
      vote_count: 1,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [Array],
      id: 194238,
      original_language: "es",
      original_title: "Farmacia de guardia: la última guardia",
      overview: "",
      popularity: 0.886,
      poster_path: "/8YgtQ8iUitc6hLQOOwLqoS8awjj.jpg",
      release_date: "2010-05-17",
      title: "Farmacia de guardia: la última guardia",
      video: false,
      vote_average: 4,
      vote_count: 8,
    },
    {
      adult: false,
      backdrop_path: "/qDEZmaaAGhEso6kvB5kk1CROPwG.jpg",
      genre_ids: [Array],
      id: 897,
      original_language: "bn",
      original_title: "অপরাজিত",
      overview:
        "Aparajito picks up where the first film leaves off, with Apu and his family having moved away from the country to live in the bustling holy city of Varanasi (then known as Benares). As Apu progresses from wide-eyed child to intellectually curious teenager, eventually studying in Kolkata, we witness his academic and moral education, as well as the growing complexity of his relationship with his mother. This tenderly expressive, often heart-wrenching film, which won three top prizes at the Venice Film Festival, including the Golden Lion, not only extends but also spiritually deepens the tale of Apu.",
      popularity: 9.252,
      poster_path: "/qvR2Qs42WHwCEcuwhQnterU3gVY.jpg",
      release_date: "1956-10-11",
      title: "Aparajito",
      video: false,
      vote_average: 7.962,
      vote_count: 208,
    },
    {
      adult: false,
      backdrop_path: "/zjRkl5PZvFujbRndrNbf4ZKbeNC.jpg",
      genre_ids: [Array],
      id: 942,
      original_language: "en",
      original_title: "Lethal Weapon 2",
      overview:
        "In the opening chase, Martin Riggs and Roger Murtaugh stumble across a trunk full of Krugerrands. They follow the trail to a South African diplomat who's using his immunity to conceal a smuggling operation. When he plants a bomb under Murtaugh's toilet, the action explodes!",
      popularity: 19.275,
      poster_path: "/1EEIUw0tkX7AJZ1ikZrtKZZKlC6.jpg",
      release_date: "1989-07-07",
      title: "Lethal Weapon 2",
      video: false,
      vote_average: 7.004,
      vote_count: 3075,
    },
    {
      adult: false,
      backdrop_path: "/kmt9XmhmX36sJduuDVFlTgEWh9U.jpg",
      genre_ids: [Array],
      id: 943,
      original_language: "en",
      original_title: "Lethal Weapon 3",
      overview:
        "Archetypal buddy cops Riggs and Murtaugh are back for another round of high-stakes action, this time setting their collective sights on bringing down a former Los Angeles police lieutenant turned black market weapons dealer. Lorna Cole joins as the beautiful yet hardnosed internal affairs sergeant who catches Riggs's eye.",
      popularity: 20.964,
      poster_path: "/8FnOudDHPOY7MFJnvQMR1qpuyek.jpg",
      release_date: "1992-05-15",
      title: "Lethal Weapon 3",
      video: false,
      vote_average: 6.698,
      vote_count: 2614,
    },
    {
      adult: false,
      backdrop_path: "/u4d4vymNPo1UuJ6ihtyy9OQgco2.jpg",
      genre_ids: [Array],
      id: 944,
      original_language: "en",
      original_title: "Lethal Weapon 4",
      overview:
        "Officers Martin Riggs and Roger Murtaugh of the Los Angeles Police Department must stop a dangerous crime lord from China from getting his brother out of jail.",
      popularity: 22.76,
      poster_path: "/w8qaZ1OuBuI2NhySynW0n4kHWgT.jpg",
      release_date: "1998-07-10",
      title: "Lethal Weapon 4",
      video: false,
      vote_average: 6.572,
      vote_count: 2378,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [Array],
      id: 194585,
      original_language: "ml",
      original_title: "പൈതൃകം",
      overview:
        "The film revolves around a traditional Brahmin family and the fight between their beliefs and atheism.",
      popularity: 0.84,
      poster_path: null,
      release_date: "1992-12-31",
      title: "Paithrukam",
      video: false,
      vote_average: 7,
      vote_count: 1,
    },
    {
      adult: false,
      backdrop_path: "/rgVJ89h3hE73aZHiEpf2fOffxbf.jpg",
      genre_ids: [Array],
      id: 194126,
      original_language: "de",
      original_title: "Schwarze Sonne",
      overview:
        "A historical analysis of how groups such as the Nazi’s may use language, symbols, and religious connotation in order to come to power. It raises questions that deserve in depth analysis and consideration. Questions include: Where do legends expand our thinking and where do they bury it? When does spiritual pursuit suddenly turn into fanaticism and violence? Last, have we as a society learned from our past, and if so have forgotten the lessons of the 20th Century? Are we now embarking on a new level only to learn the same old lessons about humanity again?  In addressing these questions we are taken into the back drop of the history of Germany beginning in the late 1800’s through the late 20th Century at the eve of the 21st.  “A society that does not take archetypes, myths, and symbols seriously will possibly be jumped by them from behind.”",
      popularity: 0.6,
      poster_path: "/5zeIaHNQ3lFmOrWThbylMMcDy8g.jpg",
      release_date: "1998-05-29",
      title: "Black Sun",
      video: false,
      vote_average: 6,
      vote_count: 3,
    },
    {
      adult: false,
      backdrop_path: "/mJnj4xyAIRm43MY5VQ7Rs0djlj4.jpg",
      genre_ids: [Array],
      id: 1043922,
      original_language: "en",
      original_title: "Pothos",
      overview: "Ivy gets her first period during her first communion.",
      popularity: 0.6,
      poster_path: "/kSl2EqsKGF3R4bT03uHzgUBiqpi.jpg",
      release_date: "2020-04-30",
      title: "Pothos",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [Array],
      id: 488115,
      original_language: "en",
      original_title: "It Kills: Camp Blood 7",
      overview:
        "A group of college kids on break find themselves in a terrifying situation when they become stranded at the infamous Camp Blood.",
      popularity: 1.358,
      poster_path: "/dSGOTXQzPe21tYMZjAhOB9mqWoE.jpg",
      release_date: "2017-11-11",
      title: "It Kills: Camp Blood 7",
      video: false,
      vote_average: 5.3,
      vote_count: 11,
    },
    {
      adult: false,
      backdrop_path: "/35tBkTTIOjsrngPiDrqCz7NpKYK.jpg",
      genre_ids: [Array],
      id: 306,
      original_language: "en",
      original_title: "Beverly Hills Cop III",
      overview:
        "Back in sunny southern California and on the trail of two murderers, Axel Foley again teams up with LA cop Billy Rosewood. Soon, they discover that an amusement park is being used as a front for a massive counterfeiting ring – and it's run by the same gang that shot Billy's boss.",
      popularity: 20.641,
      poster_path: "/7vIpCkgGEfk5LZwm78nMxswLJRH.jpg",
      release_date: "1994-05-24",
      title: "Beverly Hills Cop III",
      video: false,
      vote_average: 5.859,
      vote_count: 1576,
    },
    {
      adult: false,
      backdrop_path: "/8bQbejOvAKe78RXxpkfM04n0K18.jpg",
      genre_ids: [Array],
      id: 310,
      original_language: "en",
      original_title: "Bruce Almighty",
      overview:
        "Bruce Nolan toils as a 'human interest' television reporter in Buffalo, N.Y., but despite his high ratings and the love of his beautiful girlfriend, Bruce remains unfulfilled. At the end of the worst day in his life, he angrily ridicules God—and the Almighty responds, endowing Bruce with all of His divine powers.",
      popularity: 32.112,
      poster_path: "/f0QqG14SZYYZcV4VWykVc5w13dz.jpg",
      release_date: "2003-05-23",
      title: "Bruce Almighty",
      video: false,
      vote_average: 6.706,
      vote_count: 9976,
    },
    {
      adult: false,
      backdrop_path: "/gowjlSHLu0iQSHHItUal20PYbqS.jpg",
      genre_ids: [Array],
      id: 900274,
      original_language: "es",
      original_title: "Monasterio",
      overview:
        "There is a religious congregation founded by Saint Igneous, a saint and martyr who is believed to have been burned alive for spreading the faith. Several centuries later, a young monk prepares to be part of the order and thus, redeem his sins of the past. In the ritual ceremony he realizes that the sacrifice will be greater than he expected. Between prayers and agony, the young monk without waiting obtains what he wanted: redemption by emulating Saint Igneous.",
      popularity: 0.6,
      poster_path: "/wT3d1MBVt70APb3UF1xeyIYnm2g.jpg",
      release_date: "2021-11-21",
      title: "Monastery",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/sU3gFo7Gn67zjtKXIvzJ4omcUbH.jpg",
      genre_ids: [Array],
      id: 665,
      original_language: "en",
      original_title: "Ben-Hur",
      overview:
        "In 25 AD, Judah Ben-Hur, a Jew in ancient Judea, opposes the occupying Roman empire.  Falsely accused by a Roman childhood friend-turned-overlord of trying to kill the Roman governor, he is put into slavery and his mother and sister are taken away as prisoners.  Three years later and freed by a grateful Roman galley commander whom he has rescued from drowning, he becomes an expert charioteer for Rome, all the while plotting to return to Judea, find and rescue his family, and avenge himself on his former friend.  All the while, the form and work of Jesus move in the background of his life...",
      popularity: 24.855,
      poster_path: "/j5kFu864CgS5WGG0SYVbRVrhuWk.jpg",
      release_date: "1959-11-18",
      title: "Ben-Hur",
      video: false,
      vote_average: 7.871,
      vote_count: 2442,
    },
  ],
  total_pages: 119,
  total_results: 2378,
}
