const data = {
  result: [
    {
      directors: [Array],
      genres: [Array],
      imdbId: "tt0117571",
      originalTitle: "Scream",
      streamingInfo: [Object],
      title: "Scream",
      tmdbId: 4232,
      type: "movie",
      year: 1996,
    },
    {
      directors: [Array],
      genres: [Array],
      imdbId: "tt11245972",
      originalTitle: "Scream",
      streamingInfo: [Object],
      title: "Scream",
      tmdbId: 646385,
      type: "movie",
      year: 2022,
    },
    {
      creators: [Array],
      episodeCount: 29,
      firstAirYear: 2015,
      genres: [Array],
      imdbId: "tt3921180",
      lastAirYear: 2019,
      originalTitle: "Scream: The TV Series",
      seasonCount: 3,
      seasons: [Array],
      status: [Object],
      streamingInfo: [Object],
      title: "Scream: The TV Series",
      tmdbId: 62823,
      type: "series",
    },
    {
      directors: [Array],
      genres: [Array],
      imdbId: "tt0075462",
      originalTitle: "¿Quién puede matar a un niño?",
      streamingInfo: [Object],
      title: "Who Can Kill a Child?",
      tmdbId: 43751,
      type: "movie",
      year: 1976,
    },
    {
      creators: [Array],
      episodeCount: 30,
      firstAirYear: 2019,
      genres: [Array],
      imdbId: "tt10319942",
      lastAirYear: 2019,
      originalTitle: "چیخ‎",
      seasonCount: 1,
      seasons: [Array],
      status: [Object],
      streamingInfo: [Object],
      title: "Cheekh",
      tmdbId: 90775,
      type: "series",
    },
    {
      creators: [Array],
      episodeCount: 4,
      firstAirYear: 2019,
      genres: [Array],
      imdbId: "tt10436538",
      lastAirYear: 2019,
      originalTitle: "絶叫",
      seasonCount: 1,
      seasons: [Array],
      status: [Object],
      streamingInfo: [Object],
      title: "Zekkyo",
      tmdbId: 93896,
      type: "series",
    },
    {
      directors: [Array],
      genres: [Array],
      imdbId: "tt0086262",
      originalTitle: "Scream",
      streamingInfo: [Object],
      title: "Scream",
      tmdbId: 85191,
      type: "movie",
      year: 1981,
    },
    {
      directors: [Array],
      genres: [Array],
      imdbId: "tt0312074",
      originalTitle: "Çığlık",
      streamingInfo: [Object],
      title: "Scream",
      tmdbId: 302184,
      type: "movie",
      year: 1949,
    },
    {
      directors: [Array],
      genres: [Array],
      imdbId: "tt0120082",
      originalTitle: "Scream 2",
      streamingInfo: [Object],
      title: "Scream 2",
      tmdbId: 4233,
      type: "movie",
      year: 1997,
    },
    {
      directors: [Array],
      genres: [Array],
      imdbId: "tt1262416",
      originalTitle: "Scream 4",
      streamingInfo: [Object],
      title: "Scream 4",
      tmdbId: 41446,
      type: "movie",
      year: 2011,
    },
    {
      directors: [Array],
      genres: [Array],
      imdbId: "tt0134084",
      originalTitle: "Scream 3",
      streamingInfo: [Object],
      title: "Scream 3",
      tmdbId: 4234,
      type: "movie",
      year: 2000,
    },
    {
      directors: [Array],
      genres: [Array],
      imdbId: "tt17663992",
      originalTitle: "Scream VI",
      streamingInfo: [Object],
      title: "Scream VI",
      tmdbId: 934433,
      type: "movie",
      year: 2023,
    },
    {
      directors: [Array],
      genres: [Array],
      imdbId: "tt0114367",
      originalTitle: "Screamers",
      streamingInfo: [Object],
      title: "Screamers",
      tmdbId: 9102,
      type: "movie",
      year: 1995,
    },
    {
      directors: [Array],
      genres: [Array],
      imdbId: "tt0060214",
      originalTitle: "Carry On Screaming",
      streamingInfo: [Object],
      title: "Carry On Screaming",
      tmdbId: 5060,
      type: "movie",
      year: 1966,
    },
    {
      directors: [Array],
      genres: [Array],
      imdbId: "tt0081467",
      originalTitle: "L'isola degli uomini pesce",
      streamingInfo: [Object],
      title: "Island of the Fishmen",
      tmdbId: 27905,
      type: "movie",
      year: 1979,
    },
    {
      directors: [Array],
      genres: [Array],
      imdbId: "tt0823668",
      originalTitle: "Screamers",
      streamingInfo: [Object],
      title: "Screamers",
      tmdbId: 45057,
      type: "movie",
      year: 2006,
    },
    {
      directors: [Array],
      genres: [Array],
      imdbId: "tt5531032",
      originalTitle: "#SCREAMERS",
      streamingInfo: [Object],
      title: "#SCREAMERS",
      tmdbId: 419627,
      type: "movie",
      year: 2016,
    },
    {
      directors: [Array],
      genres: [Array],
      imdbId: "tt2118624",
      originalTitle: "The Final Girls",
      streamingInfo: [Object],
      title: "The Final Girls",
      tmdbId: 293970,
      type: "movie",
      year: 2015,
    },
    {
      directors: [Array],
      genres: [Array],
      imdbId: "tt4849176",
      originalTitle: "Sneekweek",
      streamingInfo: [Object],
      title: "Scream Week",
      tmdbId: 348320,
      type: "movie",
      year: 2016,
    },
    {
      directors: [Array],
      genres: [Array],
      imdbId: "tt0143213",
      originalTitle: "Devil in the Flesh",
      streamingInfo: [Object],
      title: "Devil in the Flesh",
      tmdbId: 45431,
      type: "movie",
      year: 1998,
    },
    {
      creators: [Array],
      episodeCount: 23,
      firstAirYear: 2015,
      genres: [Array],
      imdbId: "tt4145384",
      lastAirYear: 2016,
      originalTitle: "Scream Queens",
      seasonCount: 2,
      seasons: [Array],
      status: [Object],
      streamingInfo: [Object],
      title: "Scream Queens",
      tmdbId: 62046,
      type: "series",
    },
    {
      directors: [Array],
      genres: [Array],
      imdbId: "tt0385560",
      originalTitle: "Boo",
      streamingInfo: [Object],
      title: "Boo",
      tmdbId: 20215,
      type: "movie",
      year: 2005,
    },
    {
      directors: [Array],
      genres: [Array],
      imdbId: "tt0055505",
      originalTitle: "Taste of Fear",
      streamingInfo: [Object],
      title: "Taste of Fear",
      tmdbId: 64568,
      type: "movie",
      year: 1961,
    },
    {
      directors: [Array],
      genres: [Array],
      imdbId: "tt4006058",
      originalTitle: "Sourakh",
      streamingInfo: [Object],
      title: "Screams",
      tmdbId: 333883,
      type: "movie",
      year: 1973,
    },
    {
      directors: [Array],
      genres: [Array],
      imdbId: "tt0102855",
      originalTitle: "Cerro Torre: Schrei aus Stein",
      streamingInfo: [Object],
      title: "Scream of Stone",
      tmdbId: 88893,
      type: "movie",
      year: 1991,
    },
  ],
}
