const streaming = {
  gb: [
    {
      audios: [Array],
      availableSince: 1654545630,
      link: "https://tv.apple.com/gb/movie/avengers-infinity-war/umc.cmc.2do0xuo1u4tjmqbfz1p42a0p9",
      price: [Object],
      quality: "uhd",
      service: "apple",
      streamingType: "buy",
      subtitles: [Array],
    },
    {
      audios: [Array],
      availableSince: 1654545630,
      link: "https://tv.apple.com/gb/movie/avengers-infinity-war/umc.cmc.2do0xuo1u4tjmqbfz1p42a0p9",
      price: [Object],
      quality: "uhd",
      service: "apple",
      streamingType: "rent",
      subtitles: [Array],
    },
    {
      audios: [Array],
      availableSince: 1690942349,
      link: "https://www.amazon.co.uk/gp/video/detail/B07CLZKY26/ref=atv_dp?language=en",
      price: [Object],
      quality: "uhd",
      service: "prime",
      streamingType: "rent",
      subtitles: [Array],
    },
    {
      audios: [Array],
      availableSince: 1690942349,
      link: "https://www.amazon.co.uk/gp/video/detail/B07CLZKY26/ref=atv_dp?language=en",
      price: [Object],
      quality: "hd",
      service: "prime",
      streamingType: "rent",
      subtitles: [Array],
    },
    {
      audios: [Array],
      availableSince: 1690942349,
      link: "https://www.amazon.co.uk/gp/video/detail/B07CLZKY26/ref=atv_dp?language=en",
      price: [Object],
      quality: "sd",
      service: "prime",
      streamingType: "rent",
      subtitles: [Array],
    },
    {
      audios: [Array],
      availableSince: 1690942349,
      link: "https://www.amazon.co.uk/gp/video/detail/B07CLZKY26/ref=atv_dp?language=en",
      price: [Object],
      quality: "hd",
      service: "prime",
      streamingType: "buy",
      subtitles: [Array],
    },
    {
      audios: [Array],
      availableSince: 1690965949,
      link: "https://www.amazon.co.uk/gp/video/detail/B07CLRKTWC/ref=atv_dp?language=en",
      price: [Object],
      quality: "hd",
      service: "prime",
      streamingType: "buy",
      subtitles: [Array],
    },
    {
      audios: [Array],
      availableSince: 1690965949,
      link: "https://www.amazon.co.uk/gp/video/detail/B07CLRKTWC/ref=atv_dp?language=en",
      price: [Object],
      quality: "sd",
      service: "prime",
      streamingType: "buy",
      subtitles: [Array],
    },
    {
      audios: [Array],
      availableSince: 1690942349,
      link: "https://www.amazon.co.uk/gp/video/detail/B07CLZKY26/ref=atv_dp?language=en",
      price: [Object],
      quality: "sd",
      service: "prime",
      streamingType: "buy",
      subtitles: [Array],
    },
    {
      audios: [Array],
      availableSince: 1690942349,
      link: "https://www.amazon.co.uk/gp/video/detail/B07CLZKY26/ref=atv_dp?language=en",
      price: [Object],
      quality: "uhd",
      service: "prime",
      streamingType: "buy",
      subtitles: [Array],
    },
    {
      audios: [Array],
      availableSince: 1649777168,
      link: "https://www.disneyplus.com/movies/marvel-studios-avengers-infinity-war/1WEuZ7H6y39v",
      quality: "uhd",
      service: "disney",
      streamingType: "subscription",
      subtitles: [Array],
      videoLink:
        "https://www.disneyplus.com/video/4da34214-4803-4c80-8e66-b9b4b46e1bf8",
    },
  ],
}
